/**
 *
 *
 * Copyright (C) 2020-2021  Bibliotheca Alexandrina
 *
 *
 * The JavaScript code in this page is free software: you can
 * redistribute it and/or modify it under the terms of the GNU
 * General Public License (GNU GPL) as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.  The code is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.
 *
 * As additional permission under GNU GPL version 3 section 7, you
 * may distribute non-source (e.g., minimized or compacted) forms of
 * that code without the copy of the GNU GPL normally required by
 * section 4, provided you include this license notice and a URL
 * through which recipients can access the Corresponding Source.
 *
 *
 */


/** 
 * 
 * This file holds only constants and readonly values
 * 
 */ 


export const wwwData = {
    // Internet Top-Level Domain List 
    //   (copied from https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Country_code_top-level_domains)

    //Country code top-level domain sorted by "ccTLD" field
    countryCodeTLDList: [
        { ccTLD: "ac", entity: "Ascension Island" },
        { ccTLD: "ad", entity: "Andorra" },
        { ccTLD: "ae", entity: "United Arab Emirates" },
        { ccTLD: "af", entity: "Afghanistan" },
        { ccTLD: "ag", entity: "Antigua and Barbuda" },
        { ccTLD: "ai", entity: "Anguilla" },
        { ccTLD: "al", entity: "Albania" },
        { ccTLD: "am", entity: "Armenia" },
        { ccTLD: "an", entity: "Antilles (Netherlands)" },
        { ccTLD: "ao", entity: "Angola" },
        { ccTLD: "aq", entity: "Antarctica" },
        { ccTLD: "ar", entity: "Argentina" },
        { ccTLD: "as", entity: "American Samoa" },
        { ccTLD: "at", entity: "Austria" },
        { ccTLD: "au", entity: "Australia" },
        { ccTLD: "aw", entity: "Aruba" },
        { ccTLD: "ax", entity: "Aland Islands" },
        { ccTLD: "az", entity: "Azerbaijan" },
        { ccTLD: "ba", entity: "Bosnia and Herzegovina" },
        { ccTLD: "bb", entity: "Barbados" },
        { ccTLD: "bd", entity: "Bangladesh" },
        { ccTLD: "be", entity: "Belgium" },
        { ccTLD: "bf", entity: "Burkina Faso" },
        { ccTLD: "bg", entity: "Bulgaria" },
        { ccTLD: "bh", entity: "Bahrain" },
        { ccTLD: "bi", entity: "Burundi" },
        { ccTLD: "bj", entity: "Benin" },
        { ccTLD: "bl", entity: "Saint Barthelemy" },
        { ccTLD: "bm", entity: "Bermuda" },
        { ccTLD: "bn", entity: "Brunei Darussalam" },
        { ccTLD: "bo", entity: "Bolivia" },
        { ccTLD: "bq", entity: "Bonaire, Sint Eustatius and Saba" },
        { ccTLD: "br", entity: "Brazil" },
        { ccTLD: "bs", entity: "Bahamas" },
        { ccTLD: "bt", entity: "Bhutan" },
        { ccTLD: "bv", entity: "Bouvet Island" },
        { ccTLD: "bw", entity: "Botswana" },
        { ccTLD: "by", entity: "Belarus" },
        { ccTLD: "bz", entity: "Belize" },
        { ccTLD: "ca", entity: "Canada" },
        { ccTLD: "cc", entity: "Cocos (Keeling) Islands" },
        { ccTLD: "cd", entity: "Democratic Republic of the Congo" },
        { ccTLD: "cf", entity: "Central African Republic" },
        { ccTLD: "cg", entity: "Republic of Congo" },
        { ccTLD: "ch", entity: "Switzerland" },
        { ccTLD: "ci", entity: "Cote d'Ivoire" },
        { ccTLD: "ck", entity: "Cook Islands" },
        { ccTLD: "cl", entity: "Chile" },
        { ccTLD: "cm", entity: "Cameroon" },
        { ccTLD: "cn", entity: "China" },
        { ccTLD: "co", entity: "Colombia" },
        { ccTLD: "cr", entity: "Costa Rica" },
        { ccTLD: "cu", entity: "Cuba" },
        { ccTLD: "cv", entity: "Cape Verde" },
        { ccTLD: "cw", entity: "Curaçao" },
        { ccTLD: "cx", entity: "Christmas Island" },
        { ccTLD: "cy", entity: "Cyprus" },
        { ccTLD: "cz", entity: "Czech Republic" },
        { ccTLD: "de", entity: "Germany" },
        { ccTLD: "dj", entity: "Djibouti" },
        { ccTLD: "dk", entity: "Denmark" },
        { ccTLD: "dm", entity: "Dominica" },
        { ccTLD: "do", entity: "Dominican Republic" },
        { ccTLD: "dz", entity: "Algeria" },
        { ccTLD: "ec", entity: "Ecuador" },
        { ccTLD: "ee", entity: "Estonia" },
        { ccTLD: "eg", entity: "Egypt" },
        { ccTLD: "eh", entity: "Western Sahara" },
        { ccTLD: "er", entity: "Eritrea" },
        { ccTLD: "es", entity: "Spain" },
        { ccTLD: "et", entity: "Ethiopia" },
        { ccTLD: "eu", entity: "European Union" },
        { ccTLD: "fi", entity: "Finland" },
        { ccTLD: "fj", entity: "Fiji" },
        { ccTLD: "fk", entity: "Falkland Islands (Malvinas)" },
        { ccTLD: "fm", entity: "Federated States of Micronesia" },
        { ccTLD: "fo", entity: "Faroe Islands" },
        { ccTLD: "fr", entity: "France" },
        { ccTLD: "ga", entity: "Gabon" },
        { ccTLD: "gb", entity: "United Kingdom" },
        { ccTLD: "gd", entity: "Grenada" },
        { ccTLD: "ge", entity: "Georgia" },
        { ccTLD: "gf", entity: "French Guiana" },
        { ccTLD: "gg", entity: "Guernsey" },
        { ccTLD: "gh", entity: "Ghana" },
        { ccTLD: "gi", entity: "Gibraltar" },
        { ccTLD: "gl", entity: "Greenland" },
        { ccTLD: "gm", entity: "Gambia" },
        { ccTLD: "gn", entity: "Guinea" },
        { ccTLD: "gp", entity: "Guadeloupe" },
        { ccTLD: "gq", entity: "Equatorial Guinea" },
        { ccTLD: "gr", entity: "Greece" },
        { ccTLD: "gs", entity: "South Georgia and the South Sandwich Islands" },
        { ccTLD: "gt", entity: "Guatemala" },
        { ccTLD: "gu", entity: "Guam" },
        { ccTLD: "gw", entity: "Guinea-Bissau" },
        { ccTLD: "gy", entity: "Guyana" },
        { ccTLD: "hk", entity: "Hong Kong" },
        { ccTLD: "hm", entity: "Heard Island and McDonald Islands" },
        { ccTLD: "hn", entity: "Honduras" },
        { ccTLD: "hr", entity: "Croatia" },
        { ccTLD: "ht", entity: "Haiti" },
        { ccTLD: "hu", entity: "Hungary" },
        { ccTLD: "id", entity: "Indonesia" },
        { ccTLD: "ie", entity: "Ireland" },
        { ccTLD: "il", entity: "Israel" },
        { ccTLD: "im", entity: "Isle of Man" },
        { ccTLD: "in", entity: "India" },
        { ccTLD: "io", entity: "British Indian Ocean Territory" },
        { ccTLD: "iq", entity: "Iraq" },
        { ccTLD: "ir", entity: "Islamic Republic of Iran" },
        { ccTLD: "is", entity: "Iceland" },
        { ccTLD: "it", entity: "Italy" },
        { ccTLD: "je", entity: "Jersey" },
        { ccTLD: "jm", entity: "Jamaica" },
        { ccTLD: "jo", entity: "Jordan" },
        { ccTLD: "jp", entity: "Japan" },
        { ccTLD: "ke", entity: "Kenya" },
        { ccTLD: "kg", entity: "Kyrgyzstan" },
        { ccTLD: "kh", entity: "Cambodia" },
        { ccTLD: "ki", entity: "Kiribati" },
        { ccTLD: "km", entity: "Comoros" },
        { ccTLD: "kn", entity: "Saint Kitts and Nevis" },
        { ccTLD: "kp", entity: "Democratic People's Republic of Korea" },
        { ccTLD: "kr", entity: "Republic of Korea" },
        { ccTLD: "kw", entity: "Kuwait" },
        { ccTLD: "ky", entity: "Caymen Islands" },
        { ccTLD: "kz", entity: "Kazakhstan" },
        { ccTLD: "la", entity: "Laos" },
        { ccTLD: "lb", entity: "Lebanon" },
        { ccTLD: "lc", entity: "Saint Lucia" },
        { ccTLD: "li", entity: "Liechtenstein" },
        { ccTLD: "lk", entity: "Sri Lanka" },
        { ccTLD: "lr", entity: "Liberia" },
        { ccTLD: "ls", entity: "Lesotho" },
        { ccTLD: "lt", entity: "Lithuania" },
        { ccTLD: "lu", entity: "Luxembourg" },
        { ccTLD: "lv", entity: "Latvia" },
        { ccTLD: "ly", entity: "Libya" },
        { ccTLD: "ma", entity: "Morocco" },
        { ccTLD: "mc", entity: "Monaco" },
        { ccTLD: "md", entity: "Republic of Moldova" },
        { ccTLD: "me", entity: "Montenegro" },
        { ccTLD: "mf", entity: "Saint Martin" },
        { ccTLD: "mg", entity: "Madagascar" },
        { ccTLD: "mh", entity: "Marshall Islands" },
        { ccTLD: "mk", entity: "Macedonia" },
        { ccTLD: "ml", entity: "Mali" },
        { ccTLD: "mm", entity: "Myanmar" },
        { ccTLD: "mn", entity: "Mongolia" },
        { ccTLD: "mo", entity: "Macao" },
        { ccTLD: "mp", entity: "Northern Mariana Islands" },
        { ccTLD: "mq", entity: "Martinique" },
        { ccTLD: "mr", entity: "Mauritania" },
        { ccTLD: "ms", entity: "Montserrat" },
        { ccTLD: "mt", entity: "Malta" },
        { ccTLD: "mu", entity: "Mauritius" },
        { ccTLD: "mv", entity: "Maldives" },
        { ccTLD: "mw", entity: "Malawi" },
        { ccTLD: "mx", entity: "Mexico" },
        { ccTLD: "my", entity: "Malaysia" },
        { ccTLD: "mz", entity: "Mozambique" },
        { ccTLD: "na", entity: "Namibia" },
        { ccTLD: "nc", entity: "New Caledonia" },
        { ccTLD: "ne", entity: "Niger" },
        { ccTLD: "nf", entity: "Norfolk Island" },
        { ccTLD: "ng", entity: "Nigeria" },
        { ccTLD: "ni", entity: "Nicaragua" },
        { ccTLD: "nl", entity: "Netherlands" },
        { ccTLD: "no", entity: "Norway" },
        { ccTLD: "np", entity: "Nepal" },
        { ccTLD: "nr", entity: "Nauru" },
        { ccTLD: "nu", entity: "Niue" },
        { ccTLD: "nz", entity: "New Zealand" },
        { ccTLD: "om", entity: "Oman" },
        { ccTLD: "pa", entity: "Panama" },
        { ccTLD: "pe", entity: "Peru" },
        { ccTLD: "pf", entity: "French Polynesia" },
        { ccTLD: "pg", entity: "Papua New Guinea" },
        { ccTLD: "ph", entity: "Philippines" },
        { ccTLD: "pk", entity: "Pakistan" },
        { ccTLD: "pl", entity: "Poland" },
        { ccTLD: "pm", entity: "Saint Pierre and Miquelon" },
        { ccTLD: "pn", entity: "Pitcairn" },
        { ccTLD: "pr", entity: "Puerto Rico" },
        { ccTLD: "ps", entity: "Palestine" },
        { ccTLD: "pt", entity: "Portugal" },
        { ccTLD: "pw", entity: "Palau" },
        { ccTLD: "py", entity: "Paraguay" },
        { ccTLD: "qa", entity: "Qatar" },
        { ccTLD: "re", entity: "Reunion" },
        { ccTLD: "ro", entity: "Romania" },
        { ccTLD: "rs", entity: "Serbia" },
        { ccTLD: "ru", entity: "Russia" },
        { ccTLD: "rw", entity: "Rwanda" },
        { ccTLD: "sa", entity: "Saudi Arabia" },
        { ccTLD: "sb", entity: "Solomon Islands" },
        { ccTLD: "sc", entity: "Seychelles" },
        { ccTLD: "sd", entity: "Sudan" },
        { ccTLD: "se", entity: "Sweden" },
        { ccTLD: "sg", entity: "Singapore" },
        { ccTLD: "sh", entity: "Saint Helena" },
        { ccTLD: "si", entity: "Slovenia" },
        { ccTLD: "sj", entity: "Svalbard and Jan Mayen" },
        { ccTLD: "sk", entity: "Slovakia" },
        { ccTLD: "sl", entity: "Sierra Leone" },
        { ccTLD: "sm", entity: "San Marino" },
        { ccTLD: "sn", entity: "Senegal" },
        { ccTLD: "so", entity: "Somalia" },
        { ccTLD: "sr", entity: "Suriname" },
        { ccTLD: "ss", entity: "South Sudan" },
        { ccTLD: "st", entity: "Sao Tome and Principe" },
        { ccTLD: "su", entity: "Soviet Union" },
        { ccTLD: "sv", entity: "El Salvador" },
        { ccTLD: "sx", entity: "Sint Maarten" },
        { ccTLD: "sy", entity: "Syria" },
        { ccTLD: "sz", entity: "Swaziland" },
        { ccTLD: "tc", entity: "Turks and Caicos Islands" },
        { ccTLD: "td", entity: "Chad" },
        { ccTLD: "tf", entity: "French Southern Territories" },
        { ccTLD: "tg", entity: "Togo" },
        { ccTLD: "th", entity: "Thailand" },
        { ccTLD: "tj", entity: "Tajikistan" },
        { ccTLD: "tk", entity: "Tokelau" },
        { ccTLD: "tl", entity: "Timor-Leste" },
        { ccTLD: "tm", entity: "Turkmenistan" },
        { ccTLD: "tn", entity: "Tunisia" },
        { ccTLD: "to", entity: "Tonga" },
        { ccTLD: "tp", entity: "Portuguese Timor" },
        { ccTLD: "tr", entity: "Turkey" },
        { ccTLD: "tt", entity: "Trinidad and Tobago" },
        { ccTLD: "tv", entity: "Tuvalu" },
        { ccTLD: "tw", entity: "Taiwan" },
        { ccTLD: "tz", entity: "Tanzania" },
        { ccTLD: "ua", entity: "Ukraine" },
        { ccTLD: "ug", entity: "Uganda" },
        { ccTLD: "uk", entity: "United Kingdom" },
        { ccTLD: "um", entity: "United States Minor Outlying Islands" },
        { ccTLD: "us", entity: "United States" },
        { ccTLD: "uy", entity: "Uruguay" },
        { ccTLD: "uz", entity: "Uzbekistan" },
        { ccTLD: "va", entity: "Vatican City" },
        { ccTLD: "vc", entity: "Saint Vincent and the Grenadines" },
        { ccTLD: "ve", entity: "Venezuela" },
        { ccTLD: "vg", entity: "British Virgin Islands" },
        { ccTLD: "vi", entity: "US Virgin Islands" },
        { ccTLD: "vn", entity: "Vietnam" },
        { ccTLD: "vu", entity: "Vanuatu" },
        { ccTLD: "wf", entity: "Wallis and Futuna" },
        { ccTLD: "ws", entity: "Samoa" },
        { ccTLD: "yt", entity: "Mayote" },
        { ccTLD: "za", entity: "South Africa" },
        { ccTLD: "zm", entity: "Zambia" },
        { ccTLD: "zw", entity: "Zimbabwe" },
    ],

    // File extensions
    fileExtensionList: [
        { ext: "3DM", cat: "3D Image Files", desc: "Rhino 3D Model" },
        { ext: "3DS", cat: "3D Image Files", desc: "3D Studio Scene" },
        { ext: "3G2", cat: "Video Files", desc: "3GPP2 Multimedia File" },
        { ext: "3GP", cat: "Video Files", desc: "3GPP Multimedia File" },
        { ext: "7Z", cat: "Compressed Files", desc: "7-Zip Compressed File" },
        { ext: "ACCDB", cat: "Database Files", desc: "Access 2007 Database File" },
        { ext: "AI", cat: "Vector Image Files", desc: "Adobe Illustrator File" },
        { ext: "AIF", cat: "Audio Files", desc: "Audio Interchange File Format" },
        { ext: "APK", cat: "Executable Files", desc: "Android Package File" },
        { ext: "APP", cat: "Executable Files", desc: "macOS Application" },
        { ext: "ASF", cat: "Video Files", desc: "Advanced Systems Format File" },
        { ext: "ASP", cat: "Web Files", desc: "Active Server Page" },
        { ext: "ASPX", cat: "Web Files", desc: "Active Server Page Extended File" },
        { ext: "AVI", cat: "Video Files", desc: "Audio Video Interleave File" },
        { ext: "B", cat: "Game Files", desc: "Grand Theft Auto 3 Saved Game File" },
        { ext: "BAK", cat: "Backup Files", desc: "Backup File" },
        { ext: "BAT", cat: "Executable Files", desc: "DOS Batch File" },
        { ext: "BIN", cat: "Disk Image Files", desc: "Binary Disc Image" },
        { ext: "BMP", cat: "Raster Image Files", desc: "Bitmap Image File" },
        { ext: "C", cat: "Developer Files", desc: "C/C++ Source Code File" },
        { ext: "CAB", cat: "System Files", desc: "Windows Cabinet File" },
        { ext: "CBR", cat: "Compressed Files", desc: "Comic Book RAR Archive" },
        { ext: "CER", cat: "Web Files", desc: "Internet Security Certificate" },
        { ext: "CFG", cat: "Settings Files", desc: "Configuration File" },
        { ext: "CFM", cat: "Web Files", desc: "ColdFusion Markup File" },
        { ext: "CGI", cat: "Executable Files", desc: "Common Gateway Interface Script" },
        { ext: "CLASS", cat: "Developer Files", desc: "Java Class File" },
        { ext: "COM", cat: "Executable Files", desc: "DOS Command File" },
        { ext: "CPL", cat: "System Files", desc: "Windows Control Panel Item" },
        { ext: "CPP", cat: "Developer Files", desc: "C++ Source Code File" },
        { ext: "CRDOWNLOAD", cat: "Web Files", desc: "Chrome Partially Downloaded File" },
        { ext: "CRX", cat: "Plugin Files", desc: "Chrome Extension" },
        { ext: "CS", cat: "Developer Files", desc: "C# Source Code File" },
        { ext: "CSR", cat: "Web Files", desc: "Certificate Signing Request File" },
        { ext: "CSS", cat: "Web Files", desc: "Cascading Style Sheet" },
        { ext: "CSV", cat: "Data Files", desc: "Comma Separated Values File" },
        { ext: "CUE", cat: "Disk Image Files", desc: "Cue Sheet File" },
        { ext: "CUR", cat: "System Files", desc: "Windows Cursor" },
        { ext: "DAT", cat: "Data Files", desc: "Data File" },
        { ext: "DB", cat: "Database Files", desc: "Database File" },
        { ext: "DBF", cat: "Database Files", desc: "Database File" },
        { ext: "DCR", cat: "Web Files", desc: "Shockwave Media File" },
        { ext: "DDS", cat: "Raster Image Files", desc: "DirectDraw Surface Image" },
        { ext: "DEB", cat: "Compressed Files", desc: "Debian Software Package" },
        { ext: "DEM", cat: "Game Files", desc: "Video Game Demo File" },
        { ext: "DESKTHEMEPACK", cat: "System Files", desc: "Windows 8 Desktop Theme Pack File" },
        { ext: "DLL", cat: "System Files", desc: "Dynamic Link Library" },
        { ext: "DMG", cat: "Disk Image Files", desc: "Apple Disk Image" },
        { ext: "DMP", cat: "System Files", desc: "Windows Memory Dump" },
        { ext: "DOC", cat: "Text Files", desc: "Microsoft Word Document (Legacy)" },
        { ext: "DOCX", cat: "Text Files", desc: "Microsoft Word Document" },
        { ext: "DRV", cat: "System Files", desc: "Device Driver" },
        { ext: "DTD", cat: "Developer Files", desc: "Document Type Definition File" },
        { ext: "DWG", cat: "CAD Files", desc: "AutoCAD Drawing Database File" },
        { ext: "DXF", cat: "CAD Files", desc: "Drawing Exchange Format File" },
        { ext: "EPS", cat: "Vector Image Files", desc: "Encapsulated PostScript File" },
        { ext: "EXE", cat: "Executable Files", desc: "Windows Executable File" },
        { ext: "FLA", cat: "Developer Files", desc: "Adobe Animate Animation" },
        { ext: "FLV", cat: "Video Files", desc: "Flash Video File" },
        { ext: "FNT", cat: "Font Files", desc: "Windows Font File" },
        { ext: "FON", cat: "Font Files", desc: "Windows Font Library" },
        { ext: "GADGET", cat: "Executable Files", desc: "Windows Gadget" },
        { ext: "GAM", cat: "Game Files", desc: "Saved Game File" },
        { ext: "GED", cat: "Data Files", desc: "GEDCOM Genealogy Data File" },
        { ext: "GIF", cat: "Raster Image Files", desc: "Graphical Interchange Format File" },
        { ext: "GPX", cat: "GIS Files", desc: "GPS Exchange File" },
        { ext: "GZ", cat: "Compressed Files", desc: "Gnu Zipped Archive" },
        { ext: "H", cat: "Developer Files", desc: "C/C++/Objective-C Header File" },
        { ext: "HEIC", cat: "Raster Image Files", desc: "High Efficiency Image Format" },
        { ext: "HQX", cat: "Encoded Files", desc: "BinHex 4.0 Encoded File" },
        { ext: "HTM", cat: "Web Files", desc: "Hypertext Markup Language File" },
        { ext: "HTML", cat: "Web Files", desc: "Hypertext Markup Language File" },
        { ext: "ICNS", cat: "System Files", desc: "macOS Icon Resource File" },
        { ext: "ICO", cat: "System Files", desc: "Icon File" },
        { ext: "ICS", cat: "Misc Files", desc: "Calendar File" },
        { ext: "IFF", cat: "Audio Files", desc: "Interchange File Format" },
        { ext: "INDD", cat: "Page Layout Files", desc: "Adobe InDesign Document" },
        { ext: "INI", cat: "Settings Files", desc: "Windows Initialization File" },
        { ext: "ISO", cat: "Disk Image Files", desc: "Disc Image File" },
        { ext: "JAR", cat: "Executable Files", desc: "Java Archive File" },
        { ext: "JAVA", cat: "Developer Files", desc: "Java Source Code File" },
        { ext: "JPG", cat: "Raster Image Files", desc: "JPEG Image" },
        { ext: "JS", cat: "Web Files", desc: "JavaScript File" },
        { ext: "JSP", cat: "Web Files", desc: "Java Server Page" },
        { ext: "KEY", cat: "Data Files", desc: "Apple Keynote Presentation" },
        { ext: "KEYCHAIN", cat: "Data Files", desc: "Mac OS X Keychain File" },
        { ext: "KML", cat: "GIS Files", desc: "Keyhole Markup Language File" },
        { ext: "KMZ", cat: "GIS +N94:N125Files", desc: "Google Earth Placemark File" },
        { ext: "LNK", cat: "System Files", desc: "Windows Shortcut" },
        { ext: "LOG", cat: "Text Files", desc: "Log File" },
        { ext: "LUA", cat: "Developer Files", desc: "Lua Source File" },
        { ext: "M", cat: "Developer Files", desc: "Objective-C Implementation File" },
        { ext: "M3U", cat: "Audio Files", desc: "Media Playlist File" },
        { ext: "M4A", cat: "Audio Files", desc: "MPEG-4 Audio File" },
        { ext: "M4V", cat: "Video Files", desc: "iTunes Video File" },
        { ext: "MAX", cat: "3D Image Files", desc: "3ds Max Scene File" },
        { ext: "MDB", cat: "Database Files", desc: "Microsoft Access Database" },
        { ext: "MDF", cat: "Disk Image Files", desc: "Media Disc Image File" },
        { ext: "MID", cat: "Audio Files", desc: "MIDI File" },
        { ext: "MIM", cat: "Encoded Files", desc: "Multi-Purpose Internet Mail Message File" },
        { ext: "MOV", cat: "Video Files", desc: "Apple QuickTime Movie" },
        { ext: "MP3", cat: "Audio Files", desc: "MP3 Audio File" },
        { ext: "MP4", cat: "Video Files", desc: "MPEG-4 Video File" },
        { ext: "MPA", cat: "Audio Files", desc: "MPEG-2 Audio File" },
        { ext: "MPG", cat: "Video Files", desc: "MPEG Video File" },
        { ext: "MSG", cat: "Text Files", desc: "Outlook Message Item File" },
        { ext: "MSI", cat: "Misc Files", desc: "Windows Installer Package" },
        { ext: "NES", cat: "Game Files", desc: "Nintendo (NES) ROM File" },
        { ext: "OBJ", cat: "3D Image Files", desc: "Wavefront 3D Object File" },
        { ext: "ODT", cat: "Text Files", desc: "OpenDocument Text Document" },
        { ext: "OTF", cat: "Font Files", desc: "OpenType Font" },
        { ext: "PAGES", cat: "Text Files", desc: "Apple Pages Document" },
        { ext: "PART", cat: "Misc Files", desc: "Partially Downloaded File" },
        { ext: "PCT", cat: "Page Layout Files", desc: "Picture File" },
        { ext: "PDB", cat: "Database Files", desc: "Program Database" },
        { ext: "PDF", cat: "Page Layout Files", desc: "Portable Document Format File" },
        { ext: "PHP", cat: "Web Files", desc: "PHP Source Code File" },
        { ext: "PKG", cat: "Compressed Files", desc: "Mac OS X Installer Package" },
        { ext: "PL", cat: "Developer Files", desc: "Perl Script" },
        { ext: "PLUGIN", cat: "Plugin Files", desc: "Mac OS X Plugin" },
        { ext: "PNG", cat: "Raster Image Files", desc: "Portable Network Graphic" },
        { ext: "PPT", cat: "Data Files", desc: "Microsoft PowerPoint Presentation (Legacy)" },
        { ext: "PPTX", cat: "Data Files", desc: "Microsoft PowerPoint Presentation" },
        { ext: "PRF", cat: "Settings Files", desc: "Outlook Profile File" },
        { ext: "PSD", cat: "Raster Image Files", desc: "Adobe Photoshop Document" },
        { ext: "PSPIMAGE", cat: "Raster Image Files", desc: "PaintShop Pro Image" },
        { ext: "PY", cat: "Developer Files", desc: "Python Script" },
        { ext: "RAR", cat: "Compressed Files", desc: "WinRAR Compressed Archive" },
        { ext: "RM", cat: "Video Files", desc: "RealMedia File" },
        { ext: "ROM", cat: "Game Files", desc: "N64 Game ROM File" },
        { ext: "RPM", cat: "Compressed Files", desc: "Red Hat Package Manager File" },
        { ext: "RSS", cat: "Web Files", desc: "Rich Site Summary" },
        { ext: "RTF", cat: "Text Files", desc: "Rich Text Format File" },
        { ext: "SAV", cat: "Game Files", desc: "Saved Game" },
        { ext: "SDF", cat: "Data Files", desc: "Standard Data File" },
        { ext: "SH", cat: "Developer Files", desc: "Bash Shell Script" },
        { ext: "SITX", cat: "Compressed Files", desc: "StuffIt X Archive" },
        { ext: "SLN", cat: "Developer Files", desc: "Visual Studio Solution File" },
        { ext: "SQL", cat: "Database Files", desc: "Structured Query Language Data File" },
        { ext: "SRT", cat: "Video Files", desc: "SubRip Subtitle File" },
        { ext: "SVG", cat: "Vector Image Files", desc: "Scalable Vector Graphics File" },
        { ext: "SWF", cat: "Video Files", desc: "Shockwave Flash Movie" },
        { ext: "SWIFT", cat: "Developer Files", desc: "Swift Source Code File" },
        { ext: "SYS", cat: "System Files", desc: "Windows System File" },
        { ext: "TAR", cat: "Data Files", desc: "Consolidated Unix File Archive" },
        { ext: "TAR.Gcat:Z", cat: "Compressed Files", desc: "Compressed Tarball File" },
        { ext: "TAX2016", cat: "Data Files", desc: "TurboTax 2016 Tax Return" },
        { ext: "TAX2020", cat: "Data Files", desc: "TurboTax 2020 Tax Return" },
        { ext: "TEX", cat: "Text Files", desc: "LaTeX Source Document" },
        { ext: "TGA", cat: "Raster Image Files", desc: "Targa Graphic" },
        { ext: "THM", cat: "Raster Image Files", desc: "Thumbnail Image File" },
        { ext: "TIF", cat: "Raster Image Files", desc: "Tagged Image File" },
        { ext: "TIFF", cat: "Raster Image Files", desc: "Tagged Image File Format" },
        { ext: "TMP", cat: "Backup Files", desc: "Temporary File" },
        { ext: "TOAST", cat: "Disk Image Files", desc: "Toast Disc Image" },
        { ext: "TORRENT", cat: "Misc Files", desc: "BitTorrent File" },
        { ext: "TTF", cat: "Font Files", desc: "TrueType Font" },
        { ext: "TXT", cat: "Text Files", desc: "Plain Text File" },
        { ext: "UUE", cat: "Encoded Files", desc: "Uuencoded File" },
        { ext: "VB", cat: "Developer Files", desc: "Visual Basic Project Item File" },
        { ext: "VCD", cat: "Disk Image Files", desc: "Virtual CD" },
        { ext: "VCF", cat: "Data Files", desc: "vCard File" },
        { ext: "VCXPROJ", cat: "Developer Files", desc: "Visual C++ Project" },
        { ext: "VOB", cat: "Video Files", desc: "DVD Video Object File" },
        { ext: "WAV", cat: "Audio Files", desc: "WAVE Audio File" },
        { ext: "WMA", cat: "Audio Files", desc: "Windows Media Audio File" },
        { ext: "WMV", cat: "Video Files", desc: "Windows Media Video" },
        { ext: "WPD", cat: "Text Files", desc: "WordPerfect Document" },
        { ext: "WPS", cat: "Text Files", desc: "Microsoft Works Word Processor Document" },
        { ext: "WSF", cat: "Executable Files", desc: "Windows Script File" },
        { ext: "XCODEPROJ", cat: "Developer Files", desc: "Xcode Project" },
        { ext: "XHTML", cat: "Web Files", desc: "Extensible Hypertext Markup Language File" },
        { ext: "XLR", cat: "Spreadsheet Files", desc: "Works Spreadsheet" },
        { ext: "XLS", cat: "Spreadsheet Files", desc: "Microsoft Excel Spreadsheet (Legacy)" },
        { ext: "XLSX", cat: "Spreadsheet Files", desc: "Microsoft Excel Spreadsheet" },
        { ext: "XML", cat: "Data Files", desc: "XML File" },
        { ext: "YUV", cat: "Raster Image Files", desc: "YUV Encoded Image File" },
        { ext: "ZIP", cat: "Compressed Files", desc: "Zipped File" },
        { ext: "ZIPX", cat: "Compressed Files", desc: "Extended Zip Archive" },
    ],
}